### ISSUE TITLE
JupyterLab instructions outdated

### ISSUE THREAD

**Issue by dpsanders** [JuliaGizmos/WebIO.jl#228]
The instruction
```
cd(Pkg.dir("WebIO", "assets"))
```
no longer works on Julia 1.0. 

What is the alternative?

**Comment by dpsanders** [comment]
I followed the instructions and they seemed to work, but I'm getting
```
WebIO not detected.
```
in JupyterLab.

**Comment by oschulz** [comment]
I'm also at a loss, at the moment - there's no "assets" directory an longer, I get a message "Loading WebIO Jupyter extension on an ad-hoc basis. Consider enabling the WebIO nbextension..." in Jupyter notebook but still an error "WebIO not detected.". But what's the new way of enabeling the WebIO nbextension?

**Comment by oschulz** [comment]
The problem seems to occur when using custom values for `JUPYTER_CONFIG_DIR` and `JUPYTER_DATA_DIR`, WebIO's "build.jl" uses `joinpath(homedir(), ...)` explicitly.

**Comment by travigd** [comment]
We're currently working on JupyterLab. For now, you may wish to pin to the latest `0.4.x` release. Currently that's `0.4.2`.

> I'm also at a loss, at the moment - there's no "assets" directory an longer, I get a message "Loading WebIO Jupyter extension on an ad-hoc basis. Consider enabling the WebIO nbextension..." in Jupyter notebook but still an error "WebIO not detected.". But what's the new way of enabeling the WebIO nbextension?

Sorry for the outdated documentation! The "ad-hoc" mode _should_ work. Are there any error messages in the console? Can you let me know which browser and version your using as well as your version of IJulia?

> The problem seems to occur when using custom values for JUPYTER_CONFIG_DIR and JUPYTER_DATA_DIR, WebIO's "build.jl" uses joinpath(homedir(), ...) explicitly.

A pull request with this changed to check for the `JUPYTER_XXX_DIR` environment variables would be very much appreciated.

**Comment by oschulz** [comment]
> A pull request with this changed to check for the JUPYTER_XXX_DIR environment variables would be very much appreciated

Will do, as soon as I've figured out a clean solution. :-)

**Comment by oschulz** [comment]
And yes, I can confirm that at in Jupyter notebook, the ad-hoc mode work (when not setting JUPYTER_XXX_DIR). This is really nice, because we work a lot with read-only Singularity software containers, and so the user can't install an add-on into the Jupyter/Anaconda directories. But Ad-hoc mode only seems to install stuff into user-owned dirs, it's a great solution!

**Comment by oschulz** [comment]
> > A pull request with this changed to check for the JUPYTER_XXX_DIR environment variables would be very much appreciated
> 
> Will do, as soon as I've figured out a clean solution. :-)

Just did a PR on IJulia.jl, JuliaLang/IJulia.jl#796, to fix basically the same issue. Should be able to implement similar solution for WebIO.jl.

**Comment by travigd** [comment]
The install process now uses the directories returned by the `jupyter` command so this should be fixed.

**Comment by shashi** [comment]
@travigd if you didn't know, when someone installs IJulia without having installed jupyter, it installs a jupyter inside the Conda.jl package's deps directory.

We should probably need to try a bit harder to detect and load IJulia if it's installed. `IJulia.jupyter_data_dir()` will give you the right directory.

**Comment by oschulz** [comment]
Could we reopen this? "build.jl" still uses `config_file = joinpath(homedir(), ".jupyter", "jupyter_notebook_config.py")`, so I don't think this is fixed, yet (at least not fully).
